[package]
name = "keyball44-viz"
version = "0.1.0"
edition = "2024"
description = "A CLI tool to parse keyball44 QMK keymap files and output an SVG visualization"
license = "Unlicense"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
regex = "1.12"
